name: Test
on:
    - push
    - pull_request

jobs:
    jest:
        name: jest
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16]
                cache: ["npm"]

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm ci
            - run: npm test

    prettier:
        name: prettier
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16]
                cache: ["npm"]

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm ci
            - run: npx prettier --check .
